---
- name: ensure fail2ban is installed
  apt: pkg=fail2ban state=latest update_cache=true cache_valid_time={{ apt_cache_valid_time }}
  notify:
    - restart fail2ban
  when: not fail2ban_install_source

- name: clone fail2ban source
  git:
    repo: '{{ fail2ban_repo }}'
    dest: '{{ fail2ban_dest }}'
    version: '{{ fail2ban_version }}'
  when: fail2ban_install_source

- name: install fail2ban
  shell: python setup.py install
  args:
    chdir: '{{ fail2ban_dest }}'
    creates: /etc/fail2ban/installed
  when: fail2ban_install_source
  notify:
    - restart fail2ban

- name: copy init script
  copy:
    src: '{{ fail2ban_dest }}/files/debian-initd'
    dest: '/etc/init.d/fail2ban'
  when: fail2ban_install_source
  notify:
    - restart fail2ban

- name: enable fail2ban service
  service:
    name: fail2ban
    enabled: yes
  when: fail2ban_install_source

- name: ensure fail2ban is configured
  template: src={{ item }}.j2 dest=/{{ item }}
  with_items:
    - etc/fail2ban/jail.local
    - etc/fail2ban/fail2ban.local
  notify:
    - restart fail2ban

- name: Configure custom fail2ban filters
  template:
    src: 'etc/fail2ban/filter.d/filter.local.j2'
    dest: '/etc/fail2ban/filter.d/{{ item.filename | d(item.name) }}.local'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: '{{ fail2ban_filters }}'
  notify: [ 'restart fail2ban' ]
  when: ((item.name is defined and item.name) and
         (item.failregex is defined and item.failregex) and
         (item.state | d('present') not in ['absent']))

- name: Remove custom fail2ban filters if requested
  file:
    path: '/etc/fail2ban/filter.d/{{ item.filename | d(item.name) }}.local'
    state: 'absent'
  with_items: '{{ fail2ban_filters }}'
  notify: [ 'restart fail2ban' ]
  when: ((item.name is defined and item.name) and
         (item.state | d('present') in ['absent']))

- name: ensure fail2ban starts on a fresh reboot
  service: name=fail2ban state=started enabled=yes

